### ISSUE TITLE
Missing Vertical Split Bar

### ISSUE THREAD

**Issue by aadrian** [krpors/gimlet#7]
There's a horizontal Split Bar, but not a vertical one.
Especially when using on some laptops (without external monitor), or when having deep drill downs, it would be useful to be able to resize the vertical split too.

**Comment by krpors** [comment]
Sounds fair enough. In fact, a very early version had a vertical split bar but I didn't think it was of any use (at least, to me), so I removed it.

JavaFX does some weird stuff with the setting of the divider position (I wanted to save it as a user preference and such). I'll definitely check it out since I am missing it in my daily use as well. :)
